version: "3"

services:
  builder:
    build:
      context: builder
    image: leopays/leopays-builder

  leopays_node:
    build:
      context: .
      dockerfile: ./from-binaries.dockerfile
    image: leopays/leopays
    command: /opt/leopays/bin/leopays-node.sh --data-dir /data -e --http-alias=leopays_node:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    hostname: leopays_node
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - leopays-node-data-volume:/data
      #- ./data/node:/data
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  leopays_wallet:
    image: leopays/leopays
    command: /opt/leopays/bin/leopays-wallet --wallet-dir /data --http-server-address=127.0.0.1:8900 --http-alias=leopays_wallet:8900 --http-alias=localhost:8900
    hostname: leopays_wallet
    links:
      - leopays_node
    volumes:
      - leopays-wallet-data-volume:/data
      #- ./data/wallet:/data
    stop_grace_period: 10m

volumes:
  leopays-node-data-volume:
    external: true
  leopays-wallet-data-volume:
    external: true
